# Generated by Django 3.2.23 on 2025-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_stops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstop',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fuelstop',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
